# basic options
theme: jekyll-theme-minimal
title: Amirhossein Basareh
author: Amirhossein Basareh
email: basareh.ab@gmail.com
# description: 
twitter_username: jekyllrb
github_username:  jekyl
# Build settings
markdown: kramdown

