# basic options

title: Amirhossein Basareh
author: Amirhossein Basareh
email: basareh.ab@gmail.com
# description: 
twitter_username: Arimagro
github_username:  Magronox
# Build settings
markdown: kramdown
theme: minima
