# basic options

title: Amirhossein Basareh
author: Amirhossein Basareh
email: basareh.ab@gmail.com
# description: 

linkedin_username: [here](http://magronox.github.io/about)
github_username:  Magronox
#description: Welcome to my home page
# Build settings
markdown: kramdown
theme: minima
