# basic options

title: Amirhossein Basareh
author: Amirhossein Basareh
email: basareh.ab@gmail.com
# description: 

linkedin_username: [Amirhossein Basareh](https://ir.linkedin.com/in/amirhossein-basareh-5b2a0798)
github_username:  Magronox
#description: Welcome to my home page
# Build settings
markdown: kramdown
theme: minima
